version: '2'

services:
    mysql:
        image: mysql:8.0
        container_name: epgrec-una-db
        volumes:
            - epgrec-db:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: epgrec
            MYSQL_PASSWORD: epgrec
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: epgrec
            TZ: "Asia/Tokyo"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --sql-mode=""

    epgrec:
        build:
            context: epgrec_centos
        container_name: epgrec
        volumes:
            - epgrec-cron-vol:/var/spool/cron
        links:
            - mysql:mysql
        ports:
            - "80:80"
            - "8888:8888"
        devices:
            - "/dev/bus/usb:/dev/bus/usb"
        tty: true
    
volumes:
    epgrec-db:
        driver: local
    epgrec-cron-vol:
        driver: local        